// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/urijs.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  environment: {
    courseURL: "http://127.0.0.1:83/webservice/rest/server.php",
    courseId: "15"
  }
});

function generateUUID() {
  const charset = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  let result = '';
  const charsetLength = charset.length;
  for (let i = 0; i < 10; i++) {
    const randomIndex = Math.floor(Math.random() * charsetLength);
    result += charset[randomIndex];
  }
  return result;
}

export default function () {
  postman[Request]({
    name: "CREATE COURSE",
    id: "20872d49-30c7-46ec-a2ee-cabd76c6bd2c",
    method: "POST",
    address:
      "{{courseURL}}?wstoken=585a5e34abe199537fec2640b8252ef7&moodlewsrestformat=json&wsfunction=core_course_create_courses&courses[0][fullname]=" + generateUUID() + "&courses[0][shortname]=" + generateUUID() + "&courses[0][categoryid]=1&courses[0][visible]=1&courses[0][summary]=text&courses[0][enablecompletion]=0&courses[0][summaryformat]=1&courses[0][format]=topics&courses[0][numsections]=0",
    data: {},
    headers: {
      "Content-Type": "application/x-www-form-urlencoded"
    },
    post(response) {
      pm.test("Course Create Status code is 200", function () {
        pm.response.to.have.status(200);
        var response = JSON.parse(responseBody);
        console.log(response[0].id);
        postman.setEnvironmentVariable("courseId", response[0].id);
      });
    }
  });

  postman[Request]({
    name: "GET COURSE",
    id: "d5085c19-0c96-4bca-b046-5340a2889591",
    method: "GET",
    address:
      "{{courseURL}}?wstoken=585a5e34abe199537fec2640b8252ef7&wsfunction=core_course_get_courses&options[ids][0]={{courseId}}&moodlewsrestformat=json",
    post(response) {
      pm.test("Get Course Status code is 200", function () {
        pm.response.to.have.status(200);
        var legalOrganizationId = JSON.parse(responseBody);
        console.log(legalOrganizationId[0].id);
      });
    }
  });

  postman[Request]({
    name: "DELETE COURSE",
    id: "7d9456eb-c39d-44df-9203-f901d0435aa1",
    method: "DELETE",
    address:
      "{{courseURL}}?wstoken=585a5e34abe199537fec2640b8252ef7&moodlewsrestformat=json&wsfunction=core_course_delete_courses&courseids[0]={{courseId}}",
    post(response) {
      pm.test("Delete Course Status code is 200", function () {
        pm.response.to.have.status(200);
      });
    }
  });
}
